-- ═══════════════════════════════════════════════════════════
--  LEXIBOOKS — inventory seed
--  Generated from data/inventory-2026-08-01.csv
--  152 titles · 169 physical copies · 145 covers
--
--  Covers and page counts come from Open Library; every cover URL was
--  fetched and confirmed to return a real image.
--
--  Genres and age ranges are DERIVED from Open Library subject tags and
--  are only a first pass — expect gaps and the occasional wrong call, and
--  correct them in the table editor. Tropes and moods are deliberately
--  empty: those are your team's editorial judgement, and they are what
--  will make a match feel hand-picked rather than algorithmic.
--
--  Run after schema.sql. Safe to re-run.
-- ═══════════════════════════════════════════════════════════

insert into books (title, author, genre, formats, age_min, age_max, page_count, cover_url)
values
  ('Ashfall Legacy', 'Pittacus Lore', '{}', '{paperback}', 8, 12, 217, 'https://covers.openlibrary.org/b/id/11981022-L.jpg'),
  ('The House on Mango Street', 'Sandra Cisneros', '{}', '{paperback}', 8, 12, 132, 'https://covers.openlibrary.org/b/id/8804569-L.jpg'),
  ('The Girl Who Drank the Moon', 'Kelly Barnhill', '{"Fantasy"}', '{paperback}', 8, 12, 388, 'https://covers.openlibrary.org/b/id/7903958-L.jpg'),
  ('Lost in the Antarctic', 'Tod Olson', '{}', '{paperback}', 8, 12, 224, 'https://covers.openlibrary.org/b/id/8809379-L.jpg'),
  ('The House of the Scorpion', 'Nancy Farmer', '{"Science Fiction"}', '{paperback}', 13, 18, 380, 'https://covers.openlibrary.org/b/id/437175-L.jpg'),
  ('All the Light We Cannot See', 'Anthony Doerr', '{}', '{paperback}', null, null, 544, 'https://covers.openlibrary.org/b/id/14559680-L.jpg'),
  ('All Thirteen: The Incredible Cave Rescue of the Thai Boys'' Soccer Team', 'Christina Soontornvat', '{"Adventure"}', '{paperback}', 8, 12, 288, 'https://covers.openlibrary.org/b/id/10394486-L.jpg'),
  ('Brian''s Winter', 'Gary Paulsen', '{"Adventure"}', '{paperback}', 8, 12, 133, 'https://covers.openlibrary.org/b/id/239344-L.jpg'),
  ('Bob', 'Wendy Mass & Rebecca Stead', '{"Fantasy"}', '{paperback}', 8, 12, 216, 'https://covers.openlibrary.org/b/id/9171508-L.jpg'),
  ('Counting by 7s', 'Holly Goldberg Sloan', '{}', '{paperback}', 8, 12, 351, 'https://covers.openlibrary.org/b/id/7590471-L.jpg'),
  ('Theodore Boone', 'John Grisham', '{"Mystery","Adventure"}', '{paperback}', 8, 12, 268, 'https://covers.openlibrary.org/b/id/9322884-L.jpg'),
  ('Wonder', 'R.J. Palacio', '{}', '{paperback}', 13, 18, 368, 'https://covers.openlibrary.org/b/id/8223160-L.jpg'),
  ('The Left-Handed Booksellers of London', 'Garth Nix', '{"Fantasy"}', '{paperback}', 13, 18, 416, 'https://covers.openlibrary.org/b/id/10096850-L.jpg'),
  ('Percy Jackson: The Lightning Thief 1', 'Rick Riordan', '{"Fantasy"}', '{paperback}', 13, 18, 384, 'https://covers.openlibrary.org/b/id/7239831-L.jpg'),
  ('The Devil Wears Prada', 'Lauren Weisberger', '{"Humor"}', '{paperback}', null, null, 384, 'https://covers.openlibrary.org/b/id/528271-L.jpg'),
  ('Anne of Green Gables', 'L.M. Montgomery', '{}', '{paperback}', 8, 12, 309, 'https://covers.openlibrary.org/b/id/14641084-L.jpg'),
  ('The Mysterious Benedict Society', 'Trenton Lee Stewart', '{"Adventure","Science Fiction"}', '{paperback}', 8, 12, 512, 'https://covers.openlibrary.org/b/id/2378898-L.jpg'),
  ('Out of My Dreams', 'Sharon M. Draper', '{}', '{paperback}', null, null, 320, 'https://covers.openlibrary.org/b/id/14812894-L.jpg'),
  ('Smile', 'Raina Telgemeier', '{"Graphic Novel"}', '{paperback}', 13, 18, 214, 'https://covers.openlibrary.org/b/id/9147132-L.jpg'),
  ('Number the Stars', 'Lois Lowry', '{}', '{paperback}', 8, 12, 147, 'https://covers.openlibrary.org/b/id/13249599-L.jpg'),
  ('Hello Neighbor: Waking Nightmare', 'Carly Anne West', '{}', '{paperback}', null, null, null, null),
  ('Trophy Life', 'Lea Geller', '{}', '{paperback}', null, null, 364, 'https://covers.openlibrary.org/b/id/8807850-L.jpg'),
  ('Star Wars: Thrawn Ascendancy Book 1 Chaos Rising', 'Timothy Zahn', '{"Science Fiction"}', '{paperback}', null, null, 408, 'https://covers.openlibrary.org/b/id/10868649-L.jpg'),
  ('Star Wars: Aftermath Life Debt', 'Chuck Wendig', '{"Science Fiction"}', '{paperback}', null, null, 397, 'https://covers.openlibrary.org/b/id/8776682-L.jpg'),
  ('Eragon', 'Christopher Paolini', '{"Fantasy"}', '{paperback}', 13, 18, 576, 'https://covers.openlibrary.org/b/id/13921600-L.jpg'),
  ('The Heroes of Olympus: The Blood of Olympus Book 5', 'Rick Riordan', '{"Fantasy"}', '{paperback}', 8, 12, 525, 'https://covers.openlibrary.org/b/id/7303498-L.jpg'),
  ('Mockingbird', 'Kathryn Erskine', '{}', '{paperback}', 13, 18, 256, 'https://covers.openlibrary.org/b/id/6309117-L.jpg'),
  ('The Mountain in the Sea', 'Ray Nayler', '{"Science Fiction","Thriller"}', '{paperback}', null, null, 464, 'https://covers.openlibrary.org/b/id/14642507-L.jpg'),
  ('Later', 'Stephen King', '{"Horror"}', '{paperback}', 8, 12, 286, 'https://covers.openlibrary.org/b/id/14654000-L.jpg'),
  ('Orphan Train Girl', 'Christina Baker Kline', '{}', '{paperback}', 8, 12, 240, 'https://covers.openlibrary.org/b/id/8814801-L.jpg'),
  ('Aru Shah and the End of Time', 'Roshani Chokshi', '{}', '{paperback}', 8, 12, 368, 'https://covers.openlibrary.org/b/id/8184341-L.jpg'),
  ('A Good Girl''s Guide to Murder', 'Holly Jackson', '{"Mystery","Thriller"}', '{paperback}', 13, 18, 431, 'https://covers.openlibrary.org/b/id/13156188-L.jpg'),
  ('The Great Gatsby', 'F. Scott Fitzgerald', '{}', '{paperback}', 13, 18, 185, 'https://covers.openlibrary.org/b/id/10590366-L.jpg'),
  ('Persepolis: The Story of a Childhood', 'Marjane Satrapi', '{"Graphic Novel","Biography"}', '{paperback}', null, null, 160, 'https://covers.openlibrary.org/b/id/12648909-L.jpg'),
  ('The Handmaid''s Tale', 'Margaret Atwood', '{"Fantasy","Science Fiction"}', '{paperback}', null, null, 352, 'https://covers.openlibrary.org/b/id/8231851-L.jpg'),
  ('The Inheritance Games', 'Jennifer Lynn Barnes', '{"Romance","Thriller"}', '{paperback}', 13, 18, 392, 'https://covers.openlibrary.org/b/id/10472357-L.jpg'),
  ('Six', 'M. M. Vaughan', '{"Science Fiction"}', '{paperback}', 8, 12, 361, 'https://covers.openlibrary.org/b/id/10167505-L.jpg'),
  ('They Both Die at the End', 'Adam Silvera', '{"Romance","Adventure"}', '{paperback}', 13, 18, 373, 'https://covers.openlibrary.org/b/id/9280553-L.jpg'),
  ('Divergent', 'Veronica Roth', '{"Science Fiction"}', '{paperback}', 13, 18, 487, 'https://covers.openlibrary.org/b/id/13274634-L.jpg'),
  ('Miss Peregrine''s Home for Peculiar Children', 'Ransom Riggs', '{"Graphic Novel","Mystery"}', '{paperback}', 13, 18, 388, 'https://covers.openlibrary.org/b/id/14416577-L.jpg'),
  ('Quiet Power', 'Susan Cain', '{}', '{paperback}', 8, 12, 288, 'https://covers.openlibrary.org/b/id/8845710-L.jpg'),
  ('The Trials of Apollo: The Tyrant''s Tomb Book 4', 'Rick Riordan', '{}', '{paperback}', 13, 18, 448, 'https://covers.openlibrary.org/b/id/8788784-L.jpg'),
  ('A Wrinkle in Time', 'Madeleine L''Engle', '{"Science Fiction"}', '{paperback}', 13, 18, 212, 'https://covers.openlibrary.org/b/id/8709146-L.jpg'),
  ('Legend', 'Marie Lu', '{"Science Fiction"}', '{paperback}', 8, 12, 313, 'https://covers.openlibrary.org/b/id/7268930-L.jpg'),
  ('Loot: How to Steal a Fortune', 'Jude Watson', '{}', '{paperback}', null, null, null, null),
  ('Girl Talk', 'Robin Wasserman', '{}', '{paperback}', 13, 18, null, 'https://covers.openlibrary.org/b/id/9646384-L.jpg'),
  ('Sophie''s World', 'Jostein Gaarder', '{}', '{paperback}', null, null, 142, 'https://covers.openlibrary.org/b/id/10563354-L.jpg'),
  ('The Song of Achilles', 'Madeline Miller', '{}', '{paperback}', null, null, 385, 'https://covers.openlibrary.org/b/id/7098465-L.jpg'),
  ('Goodnight Moon', 'Margaret Wise Brown', '{"Picture Book"}', '{paperback}', 3, 7, 32, 'https://covers.openlibrary.org/b/id/35556-L.jpg'),
  ('The Summer I Turned Pretty', 'Jenny Han', '{}', '{paperback}', 13, 18, 272, 'https://covers.openlibrary.org/b/id/8783502-L.jpg'),
  ('It Ends With Us', 'Colleen Hoover', '{"Romance"}', '{paperback}', null, null, 384, 'https://covers.openlibrary.org/b/id/10473609-L.jpg'),
  ('The Unhoneymooners', 'Christina Lauren', '{"Romance","Humor"}', '{paperback}', null, null, 424, 'https://covers.openlibrary.org/b/id/8798616-L.jpg'),
  ('Journey to the Center of the Earth', 'Jules Verne', '{}', '{paperback}', null, null, null, 'https://covers.openlibrary.org/b/id/8359565-L.jpg'),
  ('The Shore Road Mystery', 'Franklin W. Dixon', '{"Mystery"}', '{paperback}', 8, 12, 185, 'https://covers.openlibrary.org/b/id/10985686-L.jpg'),
  ('The Call of the Wild Classics Made Easy', 'Jack London', '{}', '{paperback}', null, null, 128, 'https://covers.openlibrary.org/b/id/12393037-L.jpg'),
  ('The Match', 'Sarah Adams', '{}', '{paperback}', null, null, null, null),
  ('WALL-E', 'Disney Press', '{"Science Fiction"}', '{paperback}', 8, 12, 48, 'https://covers.openlibrary.org/b/id/9503839-L.jpg'),
  ('Attack of the Shark-Headed Zombie', 'Bill Doyle', '{}', '{paperback}', null, null, null, null),
  ('Baseball Ballerina', 'Kathryn Christaldi', '{"Picture Book"}', '{paperback}', 3, 7, 48, 'https://covers.openlibrary.org/b/id/423804-L.jpg'),
  ('The Hunger Games', 'Suzanne Collins', '{"Science Fiction"}', '{paperback}', 13, 18, 399, 'https://covers.openlibrary.org/b/id/12646537-L.jpg'),
  ('Book Scavenger', 'Jennifer Chambliss Bertman', '{"Adventure","Mystery"}', '{paperback}', 8, 12, 368, 'https://covers.openlibrary.org/b/id/9140681-L.jpg'),
  ('Oliver Twist', 'Charles Dickens', '{}', '{paperback}', 8, 12, 414, 'https://covers.openlibrary.org/b/id/13300802-L.jpg'),
  ('We Were Liars', 'E. Lockhart', '{}', '{paperback}', 13, 18, 240, 'https://covers.openlibrary.org/b/id/14425312-L.jpg'),
  ('The Adventures of Huckleberry Finn', 'Mark Twain', '{}', '{paperback}', null, null, null, 'https://covers.openlibrary.org/b/id/1237481-L.jpg'),
  ('One of Us is Lying', 'Karen M. McManus', '{"Mystery"}', '{paperback}', 13, 18, 360, 'https://covers.openlibrary.org/b/id/12503935-L.jpg'),
  ('Cinder', 'Marissa Meyer', '{"Science Fiction"}', '{paperback}', 8, 12, 416, 'https://covers.openlibrary.org/b/id/6998634-L.jpg'),
  ('Children of Time', 'Adrian Tchaikovsky', '{"Science Fiction","Adventure"}', '{paperback}', null, null, 616, 'https://covers.openlibrary.org/b/id/8264706-L.jpg'),
  ('The Wednesday Wars', 'Gary D. Schmidt', '{"Historical Fiction"}', '{paperback}', 8, 12, 330, 'https://covers.openlibrary.org/b/id/6307075-L.jpg'),
  ('The Cardboard Kingdom', 'Chad Sell', '{"Adventure","Graphic Novel"}', '{paperback}', 8, 12, 281, 'https://covers.openlibrary.org/b/id/14567604-L.jpg'),
  ('In Case You Missed It', 'Sarah Darer Littman', '{}', '{paperback}', 8, 12, 320, 'https://covers.openlibrary.org/b/id/8872880-L.jpg'),
  ('Interior Chinatown', 'Charles Yu', '{}', '{paperback}', null, null, 288, 'https://covers.openlibrary.org/b/id/9257609-L.jpg'),
  ('The Emperor and the Endless Palace', 'Justinian Huang', '{}', '{paperback}', null, null, 336, null),
  ('The Babysitter''s Club Mystery 9', 'Ann M. Martin', '{"Mystery"}', '{paperback}', 8, 12, 144, 'https://covers.openlibrary.org/b/id/6288608-L.jpg'),
  ('The God of Endings', 'Jacqueline Holland', '{"Fantasy","Thriller"}', '{paperback}', null, null, 480, 'https://covers.openlibrary.org/b/id/13248565-L.jpg'),
  ('Watership Down', 'Richard Adams', '{"Adventure","Fantasy"}', '{paperback}', 8, 12, 478, 'https://covers.openlibrary.org/b/id/6450196-L.jpg'),
  ('Strider', 'Beverly Cleary', '{}', '{paperback}', 8, 12, 176, 'https://covers.openlibrary.org/b/id/10789527-L.jpg'),
  ('Thirteen Days to Midnight', 'Patrick Carman', '{"Horror"}', '{paperback}', 8, 12, null, 'https://covers.openlibrary.org/b/id/6716720-L.jpg'),
  ('Loveless', 'Alice Oseman', '{}', '{paperback}', 13, 18, 433, 'https://covers.openlibrary.org/b/id/10484915-L.jpg'),
  ('Last Chance Books', 'Kelsey Rodkey', '{}', '{paperback}', null, null, 368, 'https://covers.openlibrary.org/b/id/10889044-L.jpg'),
  ('Perfect on Paper', 'Sophie Gonzales', '{"Romance"}', '{paperback}', 13, 18, 288, 'https://covers.openlibrary.org/b/id/10247156-L.jpg'),
  ('Of Mice and Men', 'John Steinbeck', '{}', '{paperback}', null, null, 119, 'https://covers.openlibrary.org/b/id/14319003-L.jpg'),
  ('American Born Chinese', 'Gene Luen Yang', '{"Graphic Novel"}', '{paperback}', 13, 18, 240, 'https://covers.openlibrary.org/b/id/10134498-L.jpg'),
  ('Holes', 'Louis Sachar', '{}', '{paperback}', 8, 12, 240, 'https://covers.openlibrary.org/b/id/19797-L.jpg'),
  ('The Nickel Boys', 'Colson Whitehead', '{}', '{paperback}', 13, 18, 224, 'https://covers.openlibrary.org/b/id/8747820-L.jpg'),
  ('Superhuman', 'Michael Carroll', '{"Graphic Novel","Biography"}', '{paperback}', null, null, 256, 'https://covers.openlibrary.org/b/id/10307067-L.jpg'),
  ('War Stories', 'Gordon Korman', '{}', '{paperback}', 8, 12, 240, 'https://covers.openlibrary.org/b/id/10434751-L.jpg'),
  ('Junie B. Jones and Some Sneaky Peeky Spying', 'Barbara Park', '{"Humor"}', '{paperback}', 8, 12, 66, 'https://covers.openlibrary.org/b/id/3931835-L.jpg'),
  ('The Sisters Grimm', 'Michael Buckley', '{"Fantasy","Adventure"}', '{paperback}', 8, 12, null, 'https://covers.openlibrary.org/b/id/14720141-L.jpg'),
  ('The Cruel Prince', 'Holly Black', '{"Fantasy"}', '{paperback}', 8, 12, 370, 'https://covers.openlibrary.org/b/id/8361789-L.jpg'),
  ('Invisible Emmie', 'Terri Libenson', '{"Graphic Novel"}', '{paperback}', 8, 12, 192, 'https://covers.openlibrary.org/b/id/8191110-L.jpg'),
  ('The Complete Persepolis', 'Marjane Satrapi', '{}', '{paperback}', null, null, 352, 'https://covers.openlibrary.org/b/id/13158424-L.jpg'),
  ('The Elegance of the Hedgehog', 'Muriel Barbery', '{}', '{paperback}', null, null, 325, 'https://covers.openlibrary.org/b/id/5698313-L.jpg'),
  ('Positively Izzy', 'Terri Libenson', '{"Graphic Novel"}', '{paperback}', 8, 12, 220, 'https://covers.openlibrary.org/b/id/11288829-L.jpg'),
  ('Windfall', 'Jennifer E. Smith', '{}', '{paperback}', 8, 12, 376, 'https://covers.openlibrary.org/b/id/8871029-L.jpg'),
  ('Twilight', 'Stephenie Meyer', '{"Fantasy","Science Fiction"}', '{paperback}', 13, 18, 498, 'https://covers.openlibrary.org/b/id/12641977-L.jpg'),
  ('The Cat in the Hat', 'Dr. Seuss', '{"Poetry"}', '{paperback}', 8, 12, 63, 'https://covers.openlibrary.org/b/id/11342-L.jpg'),
  ('How the Grinch Stole Christmas', 'Dr. Seuss', '{"Fantasy"}', '{paperback}', 8, 12, 64, 'https://covers.openlibrary.org/b/id/12055-L.jpg'),
  ('I See Me!', 'Sam McBratney', '{}', '{paperback}', null, null, null, null),
  ('I Survived Collector''s Toolbox', 'Lauren Tarshis', '{"Adventure"}', '{paperback}', 8, 12, null, 'https://covers.openlibrary.org/b/id/8959210-L.jpg'),
  ('Women Rowing North', 'Mary Pipher', '{}', '{paperback}', null, null, 337, 'https://covers.openlibrary.org/b/id/10185954-L.jpg'),
  ('Who Was Albert Einstein?', 'Jess Brallier', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, 105, 'https://covers.openlibrary.org/b/id/4295054-L.jpg'),
  ('Who Was Helen Keller?', 'Gare Thompson', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, 112, 'https://covers.openlibrary.org/b/id/289473-L.jpg'),
  ('Who Was Galileo?', 'Patricia Brennan Demuth', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, 105, 'https://covers.openlibrary.org/b/id/12463255-L.jpg'),
  ('Who Is Jane Goodall?', 'Roberta Edwards', '{"Biography","Nonfiction"}', '{paperback}', 13, 18, 26, 'https://covers.openlibrary.org/b/id/13731467-L.jpg'),
  ('Who Was Leonardo da Vinci?', 'Roberta Edwards', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, null, 'https://covers.openlibrary.org/b/id/289769-L.jpg'),
  ('Who Is Malala Yousafzai?', 'Dinah Brown', '{"Biography","Nonfiction"}', '{paperback}', null, null, null, 'https://covers.openlibrary.org/b/id/7401229-L.jpg'),
  ('Who Was Anne Frank?', 'Ann Abramson', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, 103, 'https://covers.openlibrary.org/b/id/12991521-L.jpg'),
  ('Who Was Steve Jobs?', 'Pam Pollack', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, 112, 'https://covers.openlibrary.org/b/id/7347489-L.jpg'),
  ('Who Is J.K. Rowling?', 'Pam Pollack', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, null, 'https://covers.openlibrary.org/b/id/15231646-L.jpg'),
  ('Who Was Thomas Alva Edison?', 'Margaret Frith', '{"Biography","Nonfiction"}', '{paperback}', 8, 12, 106, 'https://covers.openlibrary.org/b/id/289676-L.jpg'),
  ('The Idea of You', 'Robinne Lee', '{"Romance"}', '{paperback}', null, null, 372, 'https://covers.openlibrary.org/b/id/14315744-L.jpg'),
  ('The School for Good and Evil', 'Soman Chainani', '{"Fantasy"}', '{paperback}', 8, 12, 496, 'https://covers.openlibrary.org/b/id/7879561-L.jpg'),
  ('Naruto', 'Masashi Kishimoto', '{"Graphic Novel","Fantasy"}', '{paperback}', null, null, 188, 'https://covers.openlibrary.org/b/id/7335243-L.jpg'),
  ('The Tiger Rising', 'Kate DiCamillo', '{}', '{paperback}', 8, 12, 129, 'https://covers.openlibrary.org/b/id/515460-L.jpg'),
  ('Out of the Dust', 'Karen Hesse', '{"Poetry"}', '{paperback}', 8, 12, 227, 'https://covers.openlibrary.org/b/id/4977479-L.jpg'),
  ('The War That Saved My Life', 'Kimberly Brubaker Bradley', '{}', '{paperback}', 8, 12, 324, 'https://covers.openlibrary.org/b/id/7410332-L.jpg'),
  ('Keeper of the Lost Cities', 'Shannon Messenger', '{"Fantasy"}', '{paperback}', 8, 12, 512, 'https://covers.openlibrary.org/b/id/9320507-L.jpg'),
  ('Deep Blue', 'Jennifer Donnelly', '{"Fantasy"}', '{paperback}', 8, 12, 352, 'https://covers.openlibrary.org/b/id/7436606-L.jpg'),
  ('Wings of Fire The Dragonet Prophecy', 'Tui T. Sutherland', '{"Fantasy","Adventure"}', '{paperback}', 8, 12, 210, 'https://covers.openlibrary.org/b/id/9264497-L.jpg'),
  ('Outliers', 'Malcolm Gladwell', '{}', '{paperback}', null, null, 320, 'https://covers.openlibrary.org/b/id/10021591-L.jpg'),
  ('The Desert is Theirs', 'Byrd Baylor', '{}', '{paperback}', 8, 12, 32, 'https://covers.openlibrary.org/b/id/6805694-L.jpg'),
  ('The Giving Tree', 'Shel Silverstein', '{"Poetry","Humor"}', '{paperback}', 3, 7, 57, 'https://covers.openlibrary.org/b/id/8981758-L.jpg'),
  ('The Lorax', 'Dr. Seuss', '{}', '{paperback}', 8, 12, 64, 'https://covers.openlibrary.org/b/id/422253-L.jpg'),
  ('Yertle the Turtle', 'Dr. Seuss', '{"Poetry"}', '{paperback}', 3, 7, 86, 'https://covers.openlibrary.org/b/id/10230104-L.jpg'),
  ('Horton Hears a Who!', 'Dr. Seuss', '{"Fantasy","Poetry"}', '{paperback}', 8, 12, 65, 'https://covers.openlibrary.org/b/id/422050-L.jpg'),
  ('Pegasus (Series)', 'Kate O''Hearn', '{}', '{paperback}', 8, 12, null, 'https://covers.openlibrary.org/b/id/6521814-L.jpg'),
  ('One Fish two fish...', 'Dr. Seuss', '{}', '{paperback}', 8, 12, 63, 'https://covers.openlibrary.org/b/id/12096-L.jpg'),
  ('I am Not Going to Get Up Today!', 'Dr. Seuss', '{"Humor","Picture Book","Poetry"}', '{paperback}', 3, 7, 48, 'https://covers.openlibrary.org/b/id/293-L.jpg'),
  ('Fox in Socks', 'Dr. Seuss', '{"Fantasy"}', '{paperback}', 8, 12, 62, 'https://covers.openlibrary.org/b/id/8832133-L.jpg'),
  ('Put me in the zoo', 'Robert Lopshire', '{}', '{paperback}', 8, 12, 58, 'https://covers.openlibrary.org/b/id/6555006-L.jpg'),
  ('A Charlie Brown Christmas', 'Charles M. Schulz', '{"Graphic Novel"}', '{paperback}', 3, 7, 192, 'https://covers.openlibrary.org/b/id/35379-L.jpg'),
  ('Wings of Fire Graphic Novel', 'Tui T. Sutherland', '{"Fantasy"}', '{paperback}', null, null, null, null),
  ('Wings of Fire The Lost Heir', 'Tui T. Sutherland', '{"Fantasy"}', '{paperback}', 8, 12, 336, 'https://covers.openlibrary.org/b/id/7548609-L.jpg'),
  ('Wings of Fire The Lost Continent', 'Tui T. Sutherland', '{"Adventure","Fantasy"}', '{paperback}', 8, 12, 336, 'https://covers.openlibrary.org/b/id/10504114-L.jpg'),
  ('Wings of Fire The Hive Queen', 'Tui T. Sutherland', '{"Fantasy","Adventure"}', '{paperback}', 8, 12, 286, 'https://covers.openlibrary.org/b/id/10504107-L.jpg'),
  ('The Trials of Apollo: The Burning Maze Book 3', 'Rick Riordan', '{"Fantasy","Adventure"}', '{paperback}', 8, 12, 448, 'https://covers.openlibrary.org/b/id/8174272-L.jpg'),
  ('365 Days of Wonder', 'R. J. Palacio', '{}', '{paperback}', 8, 12, 480, 'https://covers.openlibrary.org/b/id/8469438-L.jpg'),
  ('The Capture', 'Kathryn Lasky', '{"Fantasy"}', '{paperback}', 8, 12, 240, 'https://covers.openlibrary.org/b/id/277622-L.jpg'),
  ('Restart', 'Gordon Korman', '{}', '{paperback}', 8, 12, 256, 'https://covers.openlibrary.org/b/id/8573234-L.jpg'),
  ('The Son of Neptune', 'Rick Riordan', '{}', '{paperback}', 8, 12, 512, 'https://covers.openlibrary.org/b/id/13012024-L.jpg'),
  ('The Trials of Apollo Book 1', 'Rick Riordan', '{}', '{paperback}', null, null, 418, 'https://covers.openlibrary.org/b/id/15191817-L.jpg'),
  ('The Heroes of Olympus: The Lost Hero Book 1', 'Rick Riordan', '{"Fantasy"}', '{paperback}', 8, 12, 556, 'https://covers.openlibrary.org/b/id/12848687-L.jpg'),
  ('The Storm Runner', 'J. C. Cervantes', '{"Fantasy"}', '{paperback}', 8, 12, 571, 'https://covers.openlibrary.org/b/id/8542635-L.jpg'),
  ('The Trials of Apollo: The Dark Prophecy Book 2', 'Rick Riordan', '{"Fantasy","Adventure"}', '{paperback}', 13, 18, 432, 'https://covers.openlibrary.org/b/id/11807743-L.jpg'),
  ('Flying Lessons', 'Kwame Alexander', '{}', '{paperback}', 8, 12, 240, 'https://covers.openlibrary.org/b/id/14598089-L.jpg'),
  ('Mr. Popper''s Penguins', 'Florence and Richard Atwater', '{}', '{paperback}', null, null, 139, 'https://covers.openlibrary.org/b/id/10487037-L.jpg'),
  ('Pokémon Handbook', 'Scholastic', '{}', '{paperback}', 8, 12, 64, 'https://covers.openlibrary.org/b/id/6947743-L.jpg'),
  ('Bud, Not Buddy', 'Christopher Paul Curtis', '{}', '{paperback}', 8, 12, 245, 'https://covers.openlibrary.org/b/id/9342833-L.jpg'),
  ('Little Dreamers', 'Vashti Harrison', '{"Biography"}', '{paperback}', 8, 12, 45, 'https://covers.openlibrary.org/b/id/13134297-L.jpg'),
  ('Because of Winn-Dixie', 'Kate DiCamillo', '{}', '{paperback}', 8, 12, 182, 'https://covers.openlibrary.org/b/id/2241356-L.jpg'),
  ('The Watsons go to Birmingham', 'Christopher Paul Curtis', '{}', '{paperback}', 8, 12, 224, 'https://covers.openlibrary.org/b/id/10323552-L.jpg'),
  ('Sarah''s Key', 'Tatiana De Rosnay', '{}', '{paperback}', null, null, 356, 'https://covers.openlibrary.org/b/id/8370189-L.jpg')
on conflict do nothing;

-- One row per physical copy; the third column is the Duplicates count.
insert into copies (book_id, condition, status)
select b.id, 'good', 'available'
from (values
  ('Ashfall Legacy', 'Pittacus Lore', 1),
  ('The House on Mango Street', 'Sandra Cisneros', 1),
  ('The Girl Who Drank the Moon', 'Kelly Barnhill', 2),
  ('Lost in the Antarctic', 'Tod Olson', 1),
  ('The House of the Scorpion', 'Nancy Farmer', 1),
  ('All the Light We Cannot See', 'Anthony Doerr', 1),
  ('All Thirteen: The Incredible Cave Rescue of the Thai Boys'' Soccer Team', 'Christina Soontornvat', 1),
  ('Brian''s Winter', 'Gary Paulsen', 1),
  ('Bob', 'Wendy Mass & Rebecca Stead', 1),
  ('Counting by 7s', 'Holly Goldberg Sloan', 1),
  ('Theodore Boone', 'John Grisham', 1),
  ('Wonder', 'R.J. Palacio', 2),
  ('The Left-Handed Booksellers of London', 'Garth Nix', 1),
  ('Percy Jackson: The Lightning Thief 1', 'Rick Riordan', 3),
  ('The Devil Wears Prada', 'Lauren Weisberger', 1),
  ('Anne of Green Gables', 'L.M. Montgomery', 1),
  ('The Mysterious Benedict Society', 'Trenton Lee Stewart', 2),
  ('Out of My Dreams', 'Sharon M. Draper', 1),
  ('Smile', 'Raina Telgemeier', 2),
  ('Number the Stars', 'Lois Lowry', 2),
  ('Hello Neighbor: Waking Nightmare', 'Carly Anne West', 1),
  ('Trophy Life', 'Lea Geller', 1),
  ('Star Wars: Thrawn Ascendancy Book 1 Chaos Rising', 'Timothy Zahn', 1),
  ('Star Wars: Aftermath Life Debt', 'Chuck Wendig', 1),
  ('Eragon', 'Christopher Paolini', 1),
  ('The Heroes of Olympus: The Blood of Olympus Book 5', 'Rick Riordan', 1),
  ('Mockingbird', 'Kathryn Erskine', 1),
  ('The Mountain in the Sea', 'Ray Nayler', 1),
  ('Later', 'Stephen King', 1),
  ('Orphan Train Girl', 'Christina Baker Kline', 1),
  ('Aru Shah and the End of Time', 'Roshani Chokshi', 1),
  ('A Good Girl''s Guide to Murder', 'Holly Jackson', 1),
  ('The Great Gatsby', 'F. Scott Fitzgerald', 1),
  ('Persepolis: The Story of a Childhood', 'Marjane Satrapi', 1),
  ('The Handmaid''s Tale', 'Margaret Atwood', 1),
  ('The Inheritance Games', 'Jennifer Lynn Barnes', 2),
  ('Six', 'M. M. Vaughan', 1),
  ('They Both Die at the End', 'Adam Silvera', 1),
  ('Divergent', 'Veronica Roth', 2),
  ('Miss Peregrine''s Home for Peculiar Children', 'Ransom Riggs', 1),
  ('Quiet Power', 'Susan Cain', 1),
  ('The Trials of Apollo: The Tyrant''s Tomb Book 4', 'Rick Riordan', 1),
  ('A Wrinkle in Time', 'Madeleine L''Engle', 1),
  ('Legend', 'Marie Lu', 1),
  ('Loot: How to Steal a Fortune', 'Jude Watson', 1),
  ('Girl Talk', 'Robin Wasserman', 1),
  ('Sophie''s World', 'Jostein Gaarder', 1),
  ('The Song of Achilles', 'Madeline Miller', 1),
  ('Goodnight Moon', 'Margaret Wise Brown', 1),
  ('The Summer I Turned Pretty', 'Jenny Han', 1),
  ('It Ends With Us', 'Colleen Hoover', 1),
  ('The Unhoneymooners', 'Christina Lauren', 1),
  ('Journey to the Center of the Earth', 'Jules Verne', 1),
  ('The Shore Road Mystery', 'Franklin W. Dixon', 1),
  ('The Call of the Wild Classics Made Easy', 'Jack London', 1),
  ('The Match', 'Sarah Adams', 1),
  ('WALL-E', 'Disney Press', 1),
  ('Attack of the Shark-Headed Zombie', 'Bill Doyle', 1),
  ('Baseball Ballerina', 'Kathryn Christaldi', 1),
  ('The Hunger Games', 'Suzanne Collins', 1),
  ('Book Scavenger', 'Jennifer Chambliss Bertman', 1),
  ('Oliver Twist', 'Charles Dickens', 1),
  ('We Were Liars', 'E. Lockhart', 1),
  ('The Adventures of Huckleberry Finn', 'Mark Twain', 1),
  ('One of Us is Lying', 'Karen M. McManus', 1),
  ('Cinder', 'Marissa Meyer', 1),
  ('Children of Time', 'Adrian Tchaikovsky', 1),
  ('The Wednesday Wars', 'Gary D. Schmidt', 1),
  ('The Cardboard Kingdom', 'Chad Sell', 1),
  ('In Case You Missed It', 'Sarah Darer Littman', 1),
  ('Interior Chinatown', 'Charles Yu', 1),
  ('The Emperor and the Endless Palace', 'Justinian Huang', 1),
  ('The Babysitter''s Club Mystery 9', 'Ann M. Martin', 1),
  ('The God of Endings', 'Jacqueline Holland', 1),
  ('Watership Down', 'Richard Adams', 1),
  ('Strider', 'Beverly Cleary', 1),
  ('Thirteen Days to Midnight', 'Patrick Carman', 1),
  ('Loveless', 'Alice Oseman', 1),
  ('Last Chance Books', 'Kelsey Rodkey', 1),
  ('Perfect on Paper', 'Sophie Gonzales', 1),
  ('Of Mice and Men', 'John Steinbeck', 1),
  ('American Born Chinese', 'Gene Luen Yang', 1),
  ('Holes', 'Louis Sachar', 2),
  ('The Nickel Boys', 'Colson Whitehead', 1),
  ('Superhuman', 'Michael Carroll', 1),
  ('War Stories', 'Gordon Korman', 1),
  ('Junie B. Jones and Some Sneaky Peeky Spying', 'Barbara Park', 1),
  ('The Sisters Grimm', 'Michael Buckley', 1),
  ('The Cruel Prince', 'Holly Black', 1),
  ('Invisible Emmie', 'Terri Libenson', 1),
  ('The Complete Persepolis', 'Marjane Satrapi', 1),
  ('The Elegance of the Hedgehog', 'Muriel Barbery', 1),
  ('Positively Izzy', 'Terri Libenson', 1),
  ('Windfall', 'Jennifer E. Smith', 1),
  ('Twilight', 'Stephenie Meyer', 1),
  ('The Cat in the Hat', 'Dr. Seuss', 1),
  ('How the Grinch Stole Christmas', 'Dr. Seuss', 2),
  ('I See Me!', 'Sam McBratney', 1),
  ('I Survived Collector''s Toolbox', 'Lauren Tarshis', 1),
  ('Women Rowing North', 'Mary Pipher', 1),
  ('Who Was Albert Einstein?', 'Jess Brallier', 1),
  ('Who Was Helen Keller?', 'Gare Thompson', 1),
  ('Who Was Galileo?', 'Patricia Brennan Demuth', 1),
  ('Who Is Jane Goodall?', 'Roberta Edwards', 1),
  ('Who Was Leonardo da Vinci?', 'Roberta Edwards', 1),
  ('Who Is Malala Yousafzai?', 'Dinah Brown', 1),
  ('Who Was Anne Frank?', 'Ann Abramson', 1),
  ('Who Was Steve Jobs?', 'Pam Pollack', 1),
  ('Who Is J.K. Rowling?', 'Pam Pollack', 1),
  ('Who Was Thomas Alva Edison?', 'Margaret Frith', 1),
  ('The Idea of You', 'Robinne Lee', 1),
  ('The School for Good and Evil', 'Soman Chainani', 1),
  ('Naruto', 'Masashi Kishimoto', 2),
  ('The Tiger Rising', 'Kate DiCamillo', 1),
  ('Out of the Dust', 'Karen Hesse', 1),
  ('The War That Saved My Life', 'Kimberly Brubaker Bradley', 1),
  ('Keeper of the Lost Cities', 'Shannon Messenger', 1),
  ('Deep Blue', 'Jennifer Donnelly', 1),
  ('Wings of Fire The Dragonet Prophecy', 'Tui T. Sutherland', 1),
  ('Outliers', 'Malcolm Gladwell', 1),
  ('The Desert is Theirs', 'Byrd Baylor', 1),
  ('The Giving Tree', 'Shel Silverstein', 1),
  ('The Lorax', 'Dr. Seuss', 1),
  ('Yertle the Turtle', 'Dr. Seuss', 1),
  ('Horton Hears a Who!', 'Dr. Seuss', 1),
  ('Pegasus (Series)', 'Kate O''Hearn', 6),
  ('One Fish two fish...', 'Dr. Seuss', 1),
  ('I am Not Going to Get Up Today!', 'Dr. Seuss', 1),
  ('Fox in Socks', 'Dr. Seuss', 1),
  ('Put me in the zoo', 'Robert Lopshire', 1),
  ('A Charlie Brown Christmas', 'Charles M. Schulz', 1),
  ('Wings of Fire Graphic Novel', 'Tui T. Sutherland', 1),
  ('Wings of Fire The Lost Heir', 'Tui T. Sutherland', 1),
  ('Wings of Fire The Lost Continent', 'Tui T. Sutherland', 1),
  ('Wings of Fire The Hive Queen', 'Tui T. Sutherland', 1),
  ('The Trials of Apollo: The Burning Maze Book 3', 'Rick Riordan', 1),
  ('365 Days of Wonder', 'R. J. Palacio', 1),
  ('The Capture', 'Kathryn Lasky', 1),
  ('Restart', 'Gordon Korman', 1),
  ('The Son of Neptune', 'Rick Riordan', 1),
  ('The Trials of Apollo Book 1', 'Rick Riordan', 1),
  ('The Heroes of Olympus: The Lost Hero Book 1', 'Rick Riordan', 1),
  ('The Storm Runner', 'J. C. Cervantes', 1),
  ('The Trials of Apollo: The Dark Prophecy Book 2', 'Rick Riordan', 1),
  ('Flying Lessons', 'Kwame Alexander', 1),
  ('Mr. Popper''s Penguins', 'Florence and Richard Atwater', 1),
  ('Pokémon Handbook', 'Scholastic', 1),
  ('Bud, Not Buddy', 'Christopher Paul Curtis', 1),
  ('Little Dreamers', 'Vashti Harrison', 1),
  ('Because of Winn-Dixie', 'Kate DiCamillo', 1),
  ('The Watsons go to Birmingham', 'Christopher Paul Curtis', 1),
  ('Sarah''s Key', 'Tatiana De Rosnay', 1)
) as v(title, author, copy_count)
join books b on lower(b.title)=lower(v.title) and lower(b.author)=lower(v.author)
cross join generate_series(1, v.copy_count)
where not exists (select 1 from copies c where c.book_id = b.id);
